AllCops:
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/ModuleLength:
  Max: 260

Metrics/MethodLength:
  Max: 25

Metrics/ParameterLists:
  Max: 10

Metrics/ClassLength:
  Max: 110

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 9

Style/Documentation:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Naming/MethodName:
  Exclude:
    - "**/google_pay_token_data*"
    - "**/sofort_source*"