# frozen_string_literal: true

module CheckoutSdk
  module Payments
    # Blik payment method configuration on a Payment Setup.
    #
    # @!attribute status
    #   @return [String] (response-only) Payment method status (e.g. "available").
    # @!attribute flags
    #   @return [Array(String)] (response-only) Diagnostic flags returned by the API.
    # @!attribute partner_code
    #   @return [String] The 6-digit Blik code generated by the customer's banking app.
    #     Pattern: ^[0-9]{6}$
    class BlikPaymentMethod
      attr_accessor :status,
                    :flags,
                    :partner_code
    end
  end
end
