# frozen_string_literal: true

module CheckoutSdk
  module Payments
    module BillingPlanType
      MERCHANT_INITIATED_BILLING = 'MERCHANT_INITIATED_BILLING'
      MERCHANT_INITIATED_BILLING_SINGLE_AGREEMENT = 'MERCHANT_INITIATED_BILLING_SINGLE_AGREEMENT'
      CHANNEL_INITIATED_BILLING = 'CHANNEL_INITIATED_BILLING'
      CHANNEL_INITIATED_BILLING_SINGLE_AGREEMENT = 'CHANNEL_INITIATED_BILLING_SINGLE_AGREEMENT'
      RECURRING_PAYMENTS = 'RECURRING_PAYMENTS'
      PRE_APPROVED_PAYMENTS = 'PRE_APPROVED_PAYMENTS'
    end
  end
end
