# frozen_string_literal: true

require 'checkout_sdk/common/abstract_file_request'
require 'checkout_sdk/common/account_type'
require 'checkout_sdk/common/customer_request'
require 'checkout_sdk/common/amount_allocations'
require 'checkout_sdk/common/currency'
require 'checkout_sdk/common/account_holder_identification'
require 'checkout_sdk/common/account_holder'
require 'checkout_sdk/common/country'
require 'checkout_sdk/common/account_holder_identification_type'
require 'checkout_sdk/common/account_holder_type'
require 'checkout_sdk/common/instrument_type'
require 'checkout_sdk/common/bank_details'
require 'checkout_sdk/common/payment_source_type'
require 'checkout_sdk/common/commission'
require 'checkout_sdk/common/address'
require 'checkout_sdk/common/phone'
require 'checkout_sdk/common/file_request'
require 'checkout_sdk/common/file_purpose'
require 'checkout_sdk/common/challenge_indicator'
require 'checkout_sdk/common/update_customer_request'
require 'checkout_sdk/common/marketplace_data'
require 'checkout_sdk/common/shipping_info'
