# frozen_string_literal: true

module CheckoutSdk
  module Common
    module PaymentSourceType
      CARD = 'card'
      ID = 'id'
      NETWORK_TOKEN = 'network_token'
      TOKEN = 'token'
      CUSTOMER = 'customer'
      D_LOCAL = 'dlocal'
      KLARNA = 'klarna'
      CURRENCY_ACCOUNT = 'currency_account'
      BALOTO = 'baloto'
      BOLETO = 'boleto'
      FAWRY = 'fawry'
      GIROPAY = 'giropay'
      IDEAL = 'ideal'
      OXXO = 'oxxo'
      PAGOFACIL = 'pagofacil'
      RAPIPAGO = 'rapipago'
      SOFORT = 'sofort'
      KNET = 'knet'
      QPAY = 'qpay'
      ALIPAY = 'alipay'
      PAYPAL = 'paypal'
      MULTIBANCO = 'multibanco'
      EPS = 'eps'
      POLI = 'poli'
      P24 = 'p24'
      BENEFITPAY = 'benefitpay'
      BANCONTACT = 'bancontact'
      TAMARA = 'tamara'
      PROVIDER_TOKEN = 'provider_token'
      BANK_ACCOUNT = 'bank_account'
      WECHATPAY = 'wechatpay'
      ALIPAY_HK = 'alipay_hk'
      ALIPAY_CN = 'alipay_cn'
      ALIPAY_PLUS = 'alipay_plus'
      GCASH = 'gcash'
      DANA = 'dana'
      KAKAOPAY = 'kakaopay'
      TRUEMONEY = 'truemoney'
      TNG = 'tng'
      AFTERPAY = 'afterpay'
      BENEFIT = 'benefit'
      MBWAY = 'mbway'
      POSTFINANCE = 'postfinance'
      STCPAY = 'stcpay'
      ALMA = 'alma'
      CV_CONNECT = 'cvconnect'
      TRUSTLY = 'trustly'
      ILLICADO = 'illicado'
      SEPA = 'sepa'
      ACH = 'ach'
      BIZUM = 'bizum'
      OCTOPUS = 'octopus'
      PLAID = 'plaid'
      SEQURA = 'sequra'
    end
  end
end
